USE [master]
GO

/****** Object:  Database [MobileApp]    Script Date: 2015-11-26 16:15:48 ******/
CREATE DATABASE [MobileApp]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'MobileApp', FILENAME = N'c:\Program Files (x86)\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\MobileApp.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'MobileApp_log', FILENAME = N'c:\Program Files (x86)\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\MobileApp_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [MobileApp] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MobileApp].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [MobileApp] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [MobileApp] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [MobileApp] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [MobileApp] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [MobileApp] SET ARITHABORT OFF 
GO

ALTER DATABASE [MobileApp] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [MobileApp] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [MobileApp] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [MobileApp] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [MobileApp] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [MobileApp] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [MobileApp] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [MobileApp] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [MobileApp] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [MobileApp] SET  DISABLE_BROKER 
GO

ALTER DATABASE [MobileApp] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [MobileApp] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [MobileApp] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [MobileApp] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [MobileApp] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [MobileApp] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [MobileApp] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [MobileApp] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [MobileApp] SET  MULTI_USER 
GO

ALTER DATABASE [MobileApp] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [MobileApp] SET DB_CHAINING OFF 
GO

ALTER DATABASE [MobileApp] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [MobileApp] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [MobileApp] SET  READ_WRITE 
GO


USE [MobileApp]
GO

/****** Object:  Table [dbo].[Photos]    Script Date: 2015-11-26 16:16:20 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[Photos](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Caption] [nvarchar](50) NOT NULL,
	[Image] [varbinary](max) NOT NULL,
	[Rotation] [int] NULL,
 CONSTRAINT [PK_Photos] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO